version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=worldcup
      - MYSQL_USER=worldcup
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  www:
    build: .
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
